const ACTION__TYPES = {
    INCREMENT_COUNTER:"INCREMENT_COUNTER",
    DECREMENT_COUNTER:"DECREMENT_COUNTER",
    RESET_COUNTER:"RESET_COUNTER",


    GET_PRODUCTS:"",
    GET_PRODUCTS_SUCCESS:"",
    GET_PRODUCTS_ERROR:""
}

export default ACTION__TYPES